// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Aftersearch: typeof import('./components/aftersearch.vue')['default']
    ButtonCom: typeof import('./components/buttonCom.vue')['default']
    CampaignButtonCom: typeof import('./components/campaignButtonCom.vue')['default']
    CampaignManagementProductCom: typeof import('./components/campaignManagement-productCom.vue')['default']
    Clickable: typeof import('./components/clickable.vue')['default']
    CMmodalCom: typeof import('./components/CMmodalCom.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    IdNumberCom: typeof import('./components/idNumberCom.vue')['default']
    ImageProduct: typeof import('./components/image-product.vue')['default']
    InfringementIndicatorsCom: typeof import('./components/infringementIndicatorsCom.vue')['default']
    LandingpageCom: typeof import('./components/landingpage-com.vue')['default']
    ListingOverviewCom: typeof import('./components/listingOverviewCom.vue')['default']
    ListingOverviewProductCom: typeof import('./components/listingOverviewProductCom.vue')['default']
    Login: typeof import('./components/login.vue')['default']
    MenuDropdownNavbar: typeof import('./components/menuDropdown-navbar.vue')['default']
    ModalListingOverviewCom: typeof import('./components/modalListingOverviewCom.vue')['default']
    Navbar: typeof import('./components/navbar.vue')['default']
    Navbar2Sticky: typeof import('./components/navbar2-sticky.vue')['default']
    NormalMenuBar: typeof import('./components/normalMenuBar.vue')['default']
    PaymentMethodsCom: typeof import('./components/paymentMethodsCom.vue')['default']
    PlatformButtonCom: typeof import('./components/platformButtonCom.vue')['default']
    PlatformDropdownCom: typeof import('./components/platformDropdownCom.vue')['default']
    Product: typeof import('./components/product.vue')['default']
    ProductReviewCom: typeof import('./components/productReviewCom.vue')['default']
    README: typeof import('./components/README.md')['default']
    ResearchStatusButtonCom: typeof import('./components/researchStatusButtonCom.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchCampaignCom: typeof import('./components/searchCampaignCom.vue')['default']
    SellersReview: typeof import('./components/sellers-review.vue')['default']
    Tooltip: typeof import('./components/tooltip.vue')['default']
  }
}

export {}
